// Generated by scripts/build-i18n.js from locales/*.json — do not edit by hand.
// Add or change strings in locales/<code>.json, then run `npm run build:i18n`.

export const DEFAULT_LOCALE = "en";
export const SUPPORTED_LOCALES = ["en","de","fr","es","uk","ru","zh","ko","hi","ar","he","fa","ur"];
export const LOCALE_META = {
    "en": {
        "htmlLang": "en",
        "nativeName": "English",
        "abbr": "EN",
        "dir": "ltr",
        "path": "/"
    },
    "de": {
        "htmlLang": "de",
        "nativeName": "Deutsch",
        "abbr": "DE",
        "dir": "ltr",
        "path": "/de/"
    },
    "fr": {
        "htmlLang": "fr",
        "nativeName": "Français",
        "abbr": "FR",
        "dir": "ltr",
        "path": "/fr/"
    },
    "es": {
        "htmlLang": "es",
        "nativeName": "Español",
        "abbr": "ES",
        "dir": "ltr",
        "path": "/es/"
    },
    "uk": {
        "htmlLang": "uk",
        "nativeName": "Українська",
        "abbr": "UK",
        "dir": "ltr",
        "path": "/uk/"
    },
    "ru": {
        "htmlLang": "ru",
        "nativeName": "Русский",
        "abbr": "RU",
        "dir": "ltr",
        "path": "/ru/"
    },
    "zh": {
        "htmlLang": "zh-Hans",
        "nativeName": "简体中文",
        "abbr": "ZH",
        "dir": "ltr",
        "path": "/zh/"
    },
    "ko": {
        "htmlLang": "ko",
        "nativeName": "한국어",
        "abbr": "KO",
        "dir": "ltr",
        "path": "/ko/"
    },
    "hi": {
        "htmlLang": "hi",
        "nativeName": "हिन्दी",
        "abbr": "HI",
        "dir": "ltr",
        "path": "/hi/"
    },
    "ar": {
        "htmlLang": "ar",
        "nativeName": "العربية",
        "abbr": "AR",
        "dir": "rtl",
        "path": "/ar/"
    },
    "he": {
        "htmlLang": "he",
        "nativeName": "עברית",
        "abbr": "HE",
        "dir": "rtl",
        "path": "/he/"
    },
    "fa": {
        "htmlLang": "fa",
        "nativeName": "فارسی",
        "abbr": "FA",
        "dir": "rtl",
        "path": "/fa/"
    },
    "ur": {
        "htmlLang": "ur",
        "nativeName": "اردو",
        "abbr": "UR",
        "dir": "rtl",
        "path": "/ur/"
    }
};

// Strings a page may need for a locale it did not load. See CROSS_LOCALE_KEYS in
// scripts/build-i18n.js for why this list is short on purpose.
export const CROSS_LOCALE_STRINGS = {
    "en": {
        "language.suggest.text": "This page is also available in English.",
        "language.suggest.cta": "Read in English",
        "language.suggest.dismiss": "Dismiss"
    },
    "de": {
        "language.suggest.text": "Diese Seite gibt es auch auf Deutsch.",
        "language.suggest.cta": "Auf Deutsch lesen",
        "language.suggest.dismiss": "Schließen"
    },
    "fr": {
        "language.suggest.text": "Cette page est aussi disponible en français.",
        "language.suggest.cta": "Lire en français",
        "language.suggest.dismiss": "Fermer"
    },
    "es": {
        "language.suggest.text": "Esta página también está disponible en español.",
        "language.suggest.cta": "Leer en español",
        "language.suggest.dismiss": "Cerrar"
    },
    "uk": {
        "language.suggest.text": "Ця сторінка також доступна українською.",
        "language.suggest.cta": "Читати українською",
        "language.suggest.dismiss": "Закрити"
    },
    "ru": {
        "language.suggest.text": "Эта страница также доступна на русском.",
        "language.suggest.cta": "Читать по-русски",
        "language.suggest.dismiss": "Закрыть"
    },
    "zh": {
        "language.suggest.text": "本页面也有简体中文版本。",
        "language.suggest.cta": "阅读简体中文",
        "language.suggest.dismiss": "关闭"
    },
    "ko": {
        "language.suggest.text": "이 페이지는 한국어로도 볼 수 있습니다.",
        "language.suggest.cta": "한국어로 보기",
        "language.suggest.dismiss": "닫기"
    },
    "hi": {
        "language.suggest.text": "यह पृष्ठ हिन्दी में भी उपलब्ध है।",
        "language.suggest.cta": "हिन्दी में पढ़ें",
        "language.suggest.dismiss": "बंद करें"
    },
    "ar": {
        "language.suggest.text": "هذه الصفحة متوفرة أيضًا بالعربية.",
        "language.suggest.cta": "اقرأ بالعربية",
        "language.suggest.dismiss": "إغلاق"
    },
    "he": {
        "language.suggest.text": "הדף הזה זמין גם בעברית.",
        "language.suggest.cta": "לקריאה בעברית",
        "language.suggest.dismiss": "סגירה"
    },
    "fa": {
        "language.suggest.text": "این صفحه به فارسی هم در دسترس است.",
        "language.suggest.cta": "خواندن به فارسی",
        "language.suggest.dismiss": "بستن"
    },
    "ur": {
        "language.suggest.text": "یہ صفحہ اردو میں بھی دستیاب ہے۔",
        "language.suggest.cta": "اردو میں پڑھیں",
        "language.suggest.dismiss": "بند کریں"
    }
};
